apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 14-configure-pod.yaml

configMapGenerator:
  - name: game-demo-file
    files:
      - game.properties
      - user-interface.properties
  - name: game-demo
    envs:
      - 15-envs