apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-pod1.yaml
  - 02-podAlpine.yaml
  - 03-podHelloApp.yaml
  - 04-Deployment.yaml
  - 05-PersistentVolumeClaim.yaml
  - 06-StatefulSet.yaml
  - 07-Hello-ClusterIP.yaml